# Generated by Django 5.1.1 on 2026-08-29 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('GM', 'General Manager'), ('MGR', 'Manager / Team Lead'), ('TM', 'Team Member'), ('Lead', 'Team Lead / Manager'), ('Tech Lead', 'Technical Lead / Architect'), ('Senior Developer', 'Senior Developer'), ('Developer', 'Software Engineer'), ('UI/UX Designer', 'UI/UX Designer'), ('Product Manager', 'Product Manager'), ('QA Engineer', 'QA / Automation Engineer'), ('DevOps Engineer', 'DevOps / SRE Engineer'), ('Business Analyst', 'Business Analyst'), ('Member', 'Team Contributor / Member')], default='Member', max_length=64),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('GM', 'General Manager'), ('MGR', 'Manager'), ('TM', 'Team Member')], default='TM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected')], default='PENDING_APPROVAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='teams.department')),
                ('reporting_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_direct_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['role', 'user__first_name'],
            },
        ),
    ]
